// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for obras documents */
type ObrasDocumentData = Record<string, never>;
/**
 * obras document from Prismic
 *
 * - **API ID**: `obras`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ObrasDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<ObrasDocumentData>, "obras", Lang>;
export type AllDocumentTypes = ObrasDocument;
/**
 * Primary content in ObrasSlice → Primary
 *
 */
interface ObrasSliceSliceDefaultPrimary {
    /**
     * Title field in *ObrasSlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: obras_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *ObrasSlice → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: obras_slice.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * image field in *ObrasSlice → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: obras_slice.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for ObrasSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ObrasSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ObrasSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ObrasSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ObrasSlice*
 *
 */
type ObrasSliceSliceVariation = ObrasSliceSliceDefault;
/**
 * ObrasSlice Shared Slice
 *
 * - **API ID**: `obras_slice`
 * - **Description**: `ObrasSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ObrasSliceSlice = prismicT.SharedSlice<"obras_slice", ObrasSliceSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ObrasDocumentData, ObrasDocument, AllDocumentTypes, ObrasSliceSliceDefaultPrimary, ObrasSliceSliceDefault, ObrasSliceSliceVariation, ObrasSliceSlice };
    }
}
